version: '2'
services:
  couchdb:
    build:
      context: .
      dockerfile: Dockerfile-couchdb
    ports:
      - "5984:5984"
    networks:
      dbs:
        aliases:
          - couchdb

  couchdb-lucene:
    build:
      context: ../
      dockerfile: 2.1.0/Dockerfile
    networks:
      dbs:
        aliases:
          - couchdb-lucene

networks:
  dbs:
    driver: bridge
